---
name: Super Linter

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah untuk Linting Python menggunakan 'flake8'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          # Menghentikan workflow jika ada error
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Langkah untuk Linting YAML menggunakan 'yamllint'
      - name: Run yamllint
        uses: docker://cytopia/yamllint
        with:
          args: .
